n = int(input('Digite um numero para ver sua tabuada:'))
print('-'*12)
print(f'{n} X {1:2} = {n*1}')
print(f'{n} X {2:2} = {n*2}')
print(f'{n} X {3:2} = {n*3}')
print(f'{n} X {4:2} = {n*4}')
print(f'{n} X {5:2} = {n*5}')
print(f'{n} X {6:2} = {n*6}')
print(f'{n} X {7:2} = {n*7}')
print(f'{n} X {8:2} = {n*8}')
print(f'{n} X {9:2} = {n*9}')
print(f'{n} X {10} = {n*10}')
print('-'*12)

